### ISSUE TITLE
Support picking levels in @From annotation 

### ISSUE THREAD

**Issue by xjj59307** [dakusui/jcunit#123]
It is very common to create conditions just to pick specific levels of a certain factor. It would be convenient to be capable of selecting levels in From annotation.

`
@From(factor = "xyz", levels = {level1, level2})
`

**Comment by xjj59307** [comment]
Since java doesn't support using Object in annotation, we have to come up with another way.

**Comment by dakusui** [comment]
The intention is reasonable and I think the requirement itself should be satisfied somehow.
I would re-open this issue and try to come up with another solution.

**Comment by xjj59307** [comment]
As discussed today, do we have to create such a general feature supporting calling arbitrary method from given? Could we provide a simple built-in function just supporting picking levels?

**Comment by dakusui** [comment]
The feature I'm going to introduce will look like this.

```java
  @ParameterSource
  public Parameter.Factory a() {
    return ParameterUtils.simple(1, 2, 3);
  }

  ...snip...

  @Condition
  public boolean greaterThan(int value, String strThreshold) {
    return value > Integer.parseInt(strThreshold);
  }

  @Given("greaterThan @a 2")
  public void runTest(@From("a") int a, @From("b") int b, @From("c") int c) {
    System.out.printf("runTest:(a,b,c)=(%s,%s,%s)", a, b, c);
  }
```

```runTest``` will only be executed when ```a``` is 3, which is the only level greater than 2. If you create a function ```isOneOf``` like following,

```java

 @Condition
  public boolean isOneOf(@From("@arg") int value, @From("@arg") String... values) {
    return value > Integer.parseInt(strThreshold);
  }

  @Given("isOneOf @b 2 3")
  public void runTest(@From("a") int a, @From("b") int b, @From("c") int c) {
    System.out.printf("runTest:(a,b,c)=(%s,%s,%s)", a, b, c);
  }

```

You should be able to achieve your goal.
Note that I have not yet decided to support varargs yet. It might not be introduced this time.
