### ISSUE TITLE
JCUnit fails to compile depending on JDK patch version

### ISSUE THREAD

**Issue by dakusui** [dakusui/jcunit#124]
This is a place holder ticket to report compilation issue which is found with the JDK version for JCUnit development.

Currently, the most recent JDK 8's patch release from Oracle should be used for JCUnit's development.

https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by mike-d-davydov** [comment]
Looks like it is still actual - latest code fails to compile on Java 11 latest build on Windows (11.0.1)

Here is the fix (for com.github.dakusui.jcunit8.pipeline.Pipeline):

        @SuppressWarnings("unchecked")
         private Parameter toSimpleParameterIfNecessary(Config config, Parameter parameter, List<Constraint> constraints) {
             if (!(parameter instanceof Parameter.Simple) && isInvolvedByAnyConstraint(parameter, constraints)) {
                 List<Object> values = Stream
                         .concat(
                                 (Stream<Object>)parameter.getKnownValues().stream(),
                                 engine(
                                         config, new ParameterSpace.Builder().addParameter(parameter).build())
                                         .stream().map(tuple -> tuple.get(parameter.getName())
                                 ) // Extraction
                         ).collect(toList());
                 return Parameter.Simple.Factory.of(
                         Utils.unique(
                                 values
                         ))
                         .create(parameter.getName());
             }
             return parameter;
         }

**Comment by dakusui** [comment]
Thanks a lot! I will try this fix on my linux box. Please give me output of  ```java -version```.

**Comment by mike-d-davydov** [comment]
Thanks!

Version that I've used for compilation (JDK in IntelliJ Idea project settings) is:

      java version "11.0.1" 2018-10-16 LTS
      Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
      Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)

This is Windows x64 version. I have downloaded it yesterday from Oracle.

**Comment by dakusui** [comment]
Sorry for keeping you wait.
I'm a bit busy right now and will be working on this early next week. 
Thanks again!

**Comment by mike-d-davydov** [comment]
No problems at all: I have added that comment just in case if anybody else runs into same issue...

**Comment by dakusui** [comment]
@mike-d-davydov , I realized that this can only be reproduced with JDK 11, not with JDK 8, which should be used to develop JCUnit8.
The reason to use Java 8 is because JCUnit is intended to be used various software products for various purposes and it should require dependencies and preconditions as less as possible.

Once compiled and shipped, JCUnit should be able to run under Java 11 (if not, file a bug please), but to build it, Java 8 must be used. Otherwise we can introduce dependencies or make assumptions that cannot be met by Java 8 based projects.

That being said, Java8 will not last forever and it will be replaced by Java 9, 10, 11, or more sooner or later. To start discussing such a future transition, I have filed this ticket:  #139 . (Java doesn't guarantee 100% compatibility when major version is incremented, and this sort of things have happened from time to time in history)

If the fix helps you in some way I still don't realize or you have any reason not to be able to use Java 8, please let me know, I will consider integrating the fix into development branch again.

And Thank you again for your feed back!
