### ISSUE TITLE
Defining constraints between arguments for actions in FSM

### ISSUE THREAD

**Issue by coobird** [dakusui/jcunit#31]
I have a FSM which can perform two actions, which both take arguments in common. Those arguments have constraints, which renders some combinations invalid. How would I be able to define those constraints?

**Comment by dakusui** [comment]
This is a bug in JCUnit where it lacks a way to define constraints in history of arguments.
I will fix it soon and it will be included in 0.6.0.

**Comment by dakusui** [comment]
I came to think that the model you are trying should be perhaps modified.
Because, if you have a constraint on an action which previous actions determine valid/invalid, probably the state in between those actions should be divided.

Please give me your feed back.

**Comment by dakusui** [comment]
coobird, please feel free to reopen, if you have any.
